development:
  adapter: postgresql
  database: tosakin-development
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tosakin-test
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tosakin-production
  encoding: utf8
  pool: 5
  timeout: 5000
